name: Generate Test File

#
# Only run when there is a new `new_post.md` file in the `RawRealism/content` directory.
#

on:
  push:
    branches:
      - main
    paths:
      - 'RawRealism/content/new_post.md'

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      #- name: List files in working directory pre -build
      #  run: ls -la

      #- name: List all .md files in content/posts
      #  run: find RawRealism/content/posts -name '*.md' || true

      - name: Build and run parser
        run: |
          dotnet restore RawRealism.Parser/RawRealism.Parser.csproj
          dotnet build RawRealism.Parser/RawRealism.Parser.csproj --no-restore
          dotnet run --project RawRealism.Parser/RawRealism.Parser.csproj --no-build

      - name: Commit and push generated content files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add RawRealism/content/*
          git diff --cached --quiet || git commit -m "Add/update generated content files"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout cf-pages branch
        uses: actions/checkout@v4
        with:
          ref: cf-pages
          path: cf-pages-branch

      - name: Force sync cf-pages with www content only
        run: |
          rm -rf cf-pages-branch/*
          cp -r RawRealism/www/* cf-pages-branch/

      - name: Commit and push to cf-pages
        run: |
          cd cf-pages-branch
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          # [skip ci] only needed for Cloudflare Pages if you dan't want to deploy (skip it).
          # git diff --cached --quiet || git commit -m "Sync www output to cf-pages [skip ci]"
          git diff --cached --quiet || git commit -m "Sync www output to cf-pages"
          git push origin cf-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
