name: Generate Test File

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Toon inhoud current directory
        run: ls -la

      - name: Toon inhoud van RawRealism.Parser directory
        run: ls -la RawRealism.Parser

      - name: Restore dependencies
        run: dotnet restore RawRealism.Parser/RawRealism.Parser.csproj

      - name: Build solution
        run: dotnet build RawRealism.Parser/RawRealism.Parser.csproj --no-restore

      - name: Run RawRealism.Parser
        run: dotnet run --project RawRealism.Parser/RawRealism.Parser.csproj --no-build

      - name: Show www directory contents
        run: ls -la RawRealism/www

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add generated files
        run: git add RawRealism/www

      - name: Commit changes
        id: commit-changes
        run: |
          git diff --cached --quiet || git commit -m "Auto-generate static site [skip ci]"

      - name: Push changes
        if: success() && steps.commit-changes.outcome == 'success'
        run: git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}