name: Generate Test File

on:
  push:
    branches:
      - master  # Of je default branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build solution
        run: dotnet build --no-restore

      - name: Run RawRealism.Parser
        run: dotnet run --project RawRealism.Parser/RawRealism.Parser.csproj

      - name: Show www directory contents
        run: ls -l RawRealism/www
